package com.moakiee.ae2lt.logic.tianshu;

public enum TianshuMultiblockComponent {
    AIR,
    CASING,
    GLASS,
    CONTROLLER,
    PORT,
    MAIN_BASELINE,
    MAIN_QUANTUM,
    MAIN_OVERLOAD,
    MAIN_MULTIDIMENSIONAL,
    STORAGE_CORE,
    PARALLEL_CORE,
    INVENTORY_MAINTENANCE_CORE,
    CLOSED_LOOP_PATTERN_CORE,
    CLOSED_LOOP_PATTERN_STORAGE,
    CLOSED_LOOP_SEED_STORAGE,
    OTHER
}
